export const PROFILE = {
  name: "Dahao Tang",
  title: "AI & Biology | University of Sydney",
  location: "Sydney, Australia; Nanjing, China",
  email: "dahao.tang@sydney.edu.au",
  image: "/profile.jpg",
  cvLink: "/dahao_cv.pdf",
  social: {
    github: "https://github.com/DahaoTang",
    linkedin: "https://linkedin.com/in/dahaotang",
    googleScholar:
      "https://scholar.google.com/citations?user=DPLu-fgAAAAJ&hl=en&oi=ao",
  },
};

export const EDUCATION = [
  {
    degree: "Doctor of Philosophy",
    school: "University of Sydney",
    period: "2026 — 2030",
  },
  {
    degree: "Master of Philosophy",
    school: "University of Sydney",
    period: "2025 — 2026",
  },
  {
    degree: "Bachelor of Advanced Computing (Computer Science, Honours)",
    school: "University of Sydney",
    period: "2021 — 2025",
  },
  {
    degree: "Bachelor of Commerce (Finance)",
    school: "University of Sydney",
    period: "2021 — 2025",
  },
];

export const EXPERIENCE = [
  {
    role: "Research Assistant",
    company: "David James Lab, Charles Perkins Centre, University of Sydney",
    period: "2024 Jul — Present",
    description:
      "ProteHome: A platform that stores multi-omics data and supports cross-dataset analysis",
  },
  {
    role: "Academic Tutor",
    company: "School of Computer Science, University of Sydney",
    period: "2024 Aug — 2025 Jan",
    description: "ISYS2120: Data and Information Management",
  },
];

export const PROJECTS = [
  {
    title: "LaTeX template",
    period: "2025 Dec",
    link: "https://github.com/DahaoTang/latex-templates",
    description:
      "LaTeX template, currently contains: slides (USYD-like and a casual deep-blue theme), poster (USYD-like), and a classic latex CV template",
    tags: ["LaTeX", "XeLaTex", "Makefile"],
  },
  {
    title: "Personal website",
    period: "2023 Sep - Present",
    link: "https://github.com/DahaoTang/DahaoTang.github.io",
    description: "Personal website, current version: 5",
    tags: ["Next.js", "Tailwind", "Shadcn.ui"],
  },
  {
    title: "Personal Blog (Ver. 2025 Apr)",
    period: "2024 Nov - Present",
    link: "https://github.com/DahaoTang/Blogs",
    description:
      "Personal blog, current version is based on pure html files generated by Typora from Markdown files",
    tags: ["Typora", "HTML", "Markdown"],
  },
  {
    title: "ProteHome (In Progress, link not available)",
    period: "2024 Jul - Present",
    link: "https://metabocybernetics.com/davidjames",
    description:
      "Website refactoring and full-stack development using Next.js, Django, and PostgreSQL. Decided tech stack and contributed continuously",
    tags: ["Next.js", "Django", "PostgreSQL", "Tailwind"],
  },
  {
    title: "Harper",
    period: "2024 Apr",
    link: "https://github.com/DahaoTang/Harper",
    description:
      "An AI-powered productivity assistant that bridges communication between team chat platforms and project management tools",
    tags: ["Next.js", "Slack", "OpenAI API"],
  },
  {
    title: "Émeline",
    period: "2023 Dec - 2024 Feb",
    link: "https://vimeo.com/1073007297/8ba13cb601",
    description: "Agent with smart memory (In progress)",
    tags: ["Next.js", "Convex", "OpenAI API"],
  },
  {
    title: "Next.js Authentication Template",
    period: "2024 Jan",
    link: "https://github.com/DahaoTang/nextjs-auth-server-action-template",
    description: "Nextjs authentication template using server actions",
    tags: ["Next.js", "OAuth"],
  },
];

export const PUBLICATIONS = [
  {
    title:
      "Optimal Look-back Horizon for Time Series Forecasting in Federated Learning",
    venue: "AAAI",
    year: "2026",
    authors: [
      "Dahao Tang",
      "Nan Yang",
      "Yanli Li",
      "Zhiyu Zhu",
      "Zhibo Jin",
      "Dong Yuan",
    ],
    link: "https://arxiv.org/abs/2511.12791",
  },
  {
    title:
      "Stability-Driven CNN Training with Lyapunov-Based Dynamic Learning Rate",
    venue: "ADC",
    year: "2024",
    authors: [
      "Dahao Tang",
      "Nan Yang",
      "Yongkun Deng",
      "Yuning Zhang",
      "Abubakar Sadiq Sani",
      "Dong Yuan",
    ],
    link: "https://link.springer.com/chapter/10.1007/978-981-96-1242-0_5",
  },
  {
    title:
      "Adaptformer: An Adaptive Multimodal Deep Decomposition Approach for Power Consumption Forecasting",
    venue: "ADMA",
    year: "2024",
    authors: [
      "Nan Yang",
      "Yuning Zhang",
      "Yunqi Wang",
      "Dahao Tang",
      "Yanli Li",
      "Dong Yuan",
    ],
    link: "https://link.springer.com/chapter/10.1007/978-981-96-0847-8_4",
  },
];
